//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenHistory
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public System.Guid Token { get; set; }
        public long CreatedDate { get; set; }
        public long ExpireDate { get; set; }
    }
}
